Repository NicoDazaHernandez/Request-etiquetas, pull requests merged in 2025-03, with the labels that each got.

#2 Revert "name"
  Nico Faza.txt
Labels: Diseño

#3 Revert "Revert "name""
  Nico Faza.txt
Labels: Estilo

#4 Revert "Revert "Revert "name"""
  Nico Faza.txt
Labels: Pruebas

#5 Revert "Revert "Revert "Revert "name""""
  Nico Faza.txt
Labels: Diseño

#8 Plantilla che
  Nico Faza.txt
  docs/pull_request_template.md
Labels: Diseño

#9 verifica como funciona la template al realizar pull request
  .github/pull_request_template2.md
  docs/pull_request_template.md
Labels: Pruebas
